controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

calculate_travel_cost:
    path: '/calculate-travel-cost'
    controller: 'App\Controller\TravelController::calculateTravelCost'
